export interface IPost {
    _id?: string;
    title: string;
    title_es?: string;
    title_fr?: string;
    title_it?: string;
    title_de?: string;
    title_ru?: string;
    title_ht?: string;
    slug: string;
    content: string;
    content_es?: string;
    content_fr?: string;
    content_it?: string;
    content_de?: string;
    content_ru?: string;
    content_ht?: string;
    excerpt: string;
    excerpt_es?: string;
    excerpt_fr?: string;
    excerpt_it?: string;
    excerpt_de?: string;
    excerpt_ru?: string;
    excerpt_ht?: string;
    coverImage?: string;
    author: string;
    category: 'market-update' | 'buying-guide' | 'lifestyle' | 'news';
    publishedAt: Date;
    featured: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}
