export const LOCATIONS = [
    { slug: "punta-cana", name: "Punta Cana", region: "La Altagracia", priority: true },
    { slug: "cap-cana", name: "Cap Cana", region: "La Altagracia", priority: true },
    { slug: "bavaro", name: "Bávaro", region: "La Altagracia", priority: true },
    { slug: "downtown-punta-cana", name: "Downtown Punta Cana", region: "La Altagracia", priority: true },
    { slug: "punta-cana-village", name: "Punta Cana Village", region: "La Altagracia", priority: true },
    { slug: "los-corales", name: "Los Corales", region: "La Altagracia", priority: true },
    { slug: "el-cortecito", name: "El Cortecito", region: "La Altagracia", priority: true },
    { slug: "cocotal", name: "Cocotal Golf & Country Club", region: "La Altagracia", priority: true },
    { slug: "vista-cana", name: "Vista Cana", region: "La Altagracia", priority: true },
    { slug: "cana-bay", name: "Cana Bay", region: "La Altagracia", priority: false },
    { slug: "city-place", name: "City Place", region: "La Altagracia", priority: false },
    { slug: "white-sands", name: "White Sands", region: "La Altagracia", priority: false },
    { slug: "veron", name: "Verón", region: "La Altagracia", priority: false },
    { slug: "cabeza-de-toro", name: "Cabeza de Toro", region: "La Altagracia", priority: false },
    { slug: "uvero-alto", name: "Uvero Alto", region: "La Altagracia", priority: false },
    { slug: "macao", name: "Macao", region: "La Altagracia", priority: false },
    { slug: "friusa", name: "Friusa", region: "La Altagracia", priority: false },
    { slug: "la-romana", name: "La Romana", region: "La Romana", priority: true },
    { slug: "sosua", name: "Sosúa", region: "Puerto Plata", priority: false },
];
